#INCLUDE='$(WATCOM)\h;$(WATCOM)\h\nt'
OUTOBJ=-fo=
OUTEXE=-fe=
#~ CFLAGS=-zq -ei -6s -d0 -oa
CFLAGS=-zq -d3 -od -zpw -zw
#-d3 -oa -hd
COPTS=-wx
#-i=$(INCLUDE)
LIBS=
LNK=wcl386 $(CFLAGS) 
CCC=wcc386
DBG=wdw
LIBNAME=libpvmc.lib
