echo "let projects = {"
echo "	'test.cmplGfx' : {"
echo "		base: '/Cmpl/cmplGfx/test/',"
echo "		main: 'testGfx.cmpl',"
echo "		flags: ['libGfx', 'libFile'],"
echo "		files: ["
(cd $CMPL_HOME/cmplGfx/test && find . -type f -not -name '.*' -not -path '*/tmp/*' -exec echo "			'{}'," \; | sort)
echo "		]"
echo "	},"
echo "	'test.cmplStd' : {"
echo "		base: '/Cmpl/cmplStd/test/',"
echo "		main: 'test.cmpl',"
echo "		flags: ['libFile'],"
echo "		files: ["
(cd $CMPL_HOME/cmplStd/test && find . -type f -not -name '.*' -not -path '*/tmp/*' -exec echo "			'{}'," \; | sort)
echo "		]"
echo "	},"
echo "	'test.cmplFile' : {"
echo "		base: '/Cmpl/cmplFile/test/',"
echo "		main: 'hello.world.cmpl',"
echo "		flags: ['libFile'],"
echo "		files: ["
echo "			{path: '~/out/', content: ''}, // create the output directory for temporary files"
echo "			{path: '/cmplGfx/test/asset/image/david.png', url: '/Cmpl/cmplGfx/test/asset/image/david.png'},"
echo
(cd $CMPL_HOME/cmplFile/test && find . -type f -not -name '.*' -not -path '*/out/*' -exec echo "			'{}'," \; | sort)
echo "		]"
echo "	},"
echo "};"
echo
echo "(function () {"
echo "	// add scripts saved in indexed database"
echo "	if (indexedDB.databases != null) {"
echo "		workspaceName.innerText = 's';"
echo "		indexedDB.databases().then(function(dbs) {"
echo "			let prefix = '/workspace-';"
echo "			for (db of dbs) {"
echo "				let name = db.name;"
echo "				if (!name.startsWith(prefix)) {"
echo "					continue;"
echo "				}"
echo "				name = name.substr(prefix.length);"
echo "				let url = window.location.origin + window.location.pathname + '#workspace=' + name;"
echo "				fileList.innerHTML += '<li class=\"project\" onclick=\"params.update({workspace: \'' + name + '\'});\">' + name +"
echo "					'<button class=\"right\" onclick=\"event.stopPropagation(); rmWorkspace(\'' + name + '\')\" title=\"Remove workspace\">-</button>' +"
echo "					'</li>'"
echo "			}"
echo "		}).then(function() {"
echo "			for (let demo in projects) {"
echo "				fileList.innerHTML += '<li class=\"project\" onclick=\"params.update(toProject(projects[this.textContent]));\">' + demo + '</li>'"
echo "			}"
echo "		});"
echo "	} else {"
echo "		terminal.append('Failed to list workspaces, indexedDB.databases not available');"
echo "		for (let demo in projects) {"
echo "			fileList.innerHTML += '<li class=\"project\" onclick=\"params.update(toProject(projects[this.textContent]));\">' + demo + '</li>'"
echo "		}"
echo "	}"
echo "}());"
echo
echo "function toProject(proj) {"
echo "	let project = {};"
echo
echo "	// set libraries to be used"
echo "	if (proj.flags != null) {"
echo "		for (let flag of proj.flags) {"
echo "			project[flag] = '';"
echo "		}"
echo "	}"
echo
echo "	// set files to be downloaded"
echo "	if (proj.files != null) {"
echo "		let files = [];"
echo "		for (let file of proj.files) {"
echo "			if (file != null && file.constructor === Object) {"
echo "				files.push(file);"
echo "				continue;"
echo "			}"
echo "			if (file.startsWith(proj.base)) {"
echo "				file = file.substring(proj.base.length, file.length);"
echo "			}"
echo "			let base = (proj.root || '') + (proj.base || '');"
echo "			if (!base.endsWith('/')) {"
echo "				base += '/';"
echo "			}"
echo "			files.push({"
echo "				path: file,"
echo "				url: base + file"
echo "			});"
echo "		}"
echo "		project.project = btoa(JSON.stringify(files));"
echo "	}"
echo
echo "	// set file to be opened after project is loaded"
echo "	if (proj.main != null) {"
echo "		let main = proj.main;"
echo "		if (main.startsWith(proj.base)) {"
echo "			main = main.substring(proj.base.length, main.length);"
echo "		}"
echo "		project.path = main;"
echo "	}"
echo
echo "	return project;"
echo "}"
